global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - rules.d/ssl-expire.rule
  - rules.d/up.rule

scrape_configs:
  - job_name: 'test'
    static_configs:
      - targets: ['38.145.34.215:80']

  - job_name: 'SSL Availability and Monitoring'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.distributed-ci.io/api/v1
        - https://www.distributed-ci.io
        - https://docs.distributed-ci.io
        - https://packages.distributed-ci.io
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 38.145.34.215:9115  # Blackbox exporter.

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['38.145.34.215:9093']
