global:
{% for key, value in prometheus_server_globals.iteritems()|default({}) %}
  {{ key }}: {{ value }}
{% endfor %}

rule_files:
{% for rule_file in prometheus_server_rule_files|default([]) %}
  - {{ rule_file }}
{% endfor %}

scrape_configs:
{% for scrape_config in prometheus_server_scrape_configs|default([]) %}
  - {{ scrape_config|to_nice_yaml(indent=2) }}
{% endfor %}

alerting:
  alert_relabel_configs:
{% for alert_relabel_config in prometheus_server_alert_relabel_configs|default([]) %}
    - {{ alert_relabel_config|to_nice_yaml(indent=2) }}
{% endfor %}
  alertmanagers:
{% for alertmanager in prometheus_server_alertmanagers|default([]) %}
    - {{ alertmanager|to_nice_yaml(indent=2) }}
{% endfor %}
