global:
{% for key, value in prometheus_server_globals.iteritems()|default({}) %}
  {{ key }}: {{ value }}
{% endfor %}

rule_files:
  {{ prometheus_server_rule_files|default([])|to_nice_yaml|indent(2) }}

scrape_configs:
  {{ prometheus_server_scrape_configs|default([])|to_nice_yaml|indent(2) }}

alerting:
  alert_relabel_configs:
    {{ prometheus_server_alert_relabel_configs|default([])|to_nice_yaml|indent(6) }}
  alertmanagers:
    {{ prometheus_server_alertmanagers|default([])|to_nice_yaml|indent(6) }}
